resources:
  - name: go_example
    type: GitRepo
    configuration:
      path: raksha78/NativeStep
      branches:
        include: linux
      gitProvider: raksha78_github
      
  - name: fileSpec
    type: FileSpec
    configuration:     
      sourceArtifactory: art_v
      pattern: "fileSpec_test/hello.go"
       

pipelines:
  - name: go_build_pipeline
    steps:
      - name: build_go
        type: GoBuild
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: go_example_build_publish
          sourceLocation: .
#           resolverRepo: go_local
          repository: go_local
#           noRegistry: true
#           publishDeps: true
          outputLocation: /tmp/dist
          outputFile: hello_output
          goCommand: build -o /tmp/dist/hello_output
          inputResources:
            - name: go_example
            - name: fileSpec
          integrations:
            - name: art_v
        execution:
           onStart:
              - buildDir=$(find_resource_variable $inputGitRepoResourceName resourcePath)
              - echo "******** buildDir - $buildDir"
              - pushd $buildDir
              - go get -insecure
              - popd
           onComplete:
#               - ls $step_workspace_dir/GoBuild
            
              - cd dependencyState/resources/fileSpec
              - ls .
      
