resources:
  - name: go_example
    type: GitRepo
    configuration:
      path: raksha78/NativeStep
      branches:
        include: linux
      gitProvider: raksha78_github
      
  - name: go_rak
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: go_rak
      buildNumber: 1      

pipelines:
  - name: go_build_pipeline
    steps:
      - name: build_go
        type: GoBuild
        configuration:
            environmentVariables:
                JFROG_CLI_BUILD_NAME: go_example_build_publish
            sourceLocation: .
    #           resolverRepo: go_local
            repository: go_local
    #           noRegistry: true
            outputLocation: /tmp/dist
            outputFile: hello_output
    #         goCommand: build -o /tmp/dist/hello_output
            inputResources:
                - name: go_example
            integrations:
                - name: art_v
        execution:
            onStart:
                - buildDir=$(find_resource_variable $inputGitRepoResourceName resourcePath)
                - echo "******** buildDir - $buildDir"
                - pushd $buildDir
                - go get -insecure
                - popd
            
                
      - name: publish_go_binary
        type: GoPublishBinary
        configuration:
          autoPublishBuildInfo: true
          inputSteps:
            - name: build_go
          forceXrayScan: true
          failOnScan: false
          targetRepository: go_local
          integrations:
            - name: art_v
          outputResources:
            - name: go_rak
             
