resources:
  - name: go_example
    type: GitRepo
    configuration:
      path: raksha78/NativeStep
      branches:
        include: linux
      gitProvider: raksha78_github
      
#   - name: fileSpec_publish
#     type: FileSpec
#     configuration:     
#       sourceArtifactory: art_v
#       pattern: "fileSpec_test/hello.go"
      
  - name: go_rak
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
         

pipelines:
  - name: go_build_pipeline
    steps:
      - name: publish_go_module
        type: GoPublishModule
#         execution:
#            onComplete:
#               - cd dependencyState/resources/fileSpec_publish
#               - ls .
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: go_example_module_publish
          sourceLocation: .
          version: v0.0.0
          deps: ALL
          self: true
          forceXrayScan: true
          failOnScan: false
          targetRepository: go_local
          autoPublishBuildInfo: true
          integrations:
            - name: art_v
          inputResources:
            - name: go_example
#             - name: fileSpec_publish
          outputResources:
            - name: go_rak
