resources:
  - name: go_example_1
    type: GitRepo
    configuration:
      path: raksha78/NativeStep
      branches:
        include: powershell
      gitProvider: raksha78_github
      
  - name: go_rak_1
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: go_rak_1
      buildNumber: 1      

pipelines:
  - name: go_build_pipeline_1
    configuration:
      nodePool: win_2019
    steps:
      - name: build_go_1
        type: GoBuild
        configuration:
            environmentVariables:
                JFROG_CLI_BUILD_NAME: go_example_build_publish
            sourceLocation: .
    #           resolverRepo: go_local
            repository: go_local
    #           noRegistry: true
            outputLocation: /tmp/dist
            outputFile: hello_output
    #         goCommand: build -o /tmp/dist/hello_output
            inputResources:
                - name: go_example_1
            integrations:
                - name: art_v
        execution:
            onStart:
                - $res_go_example_1_resourcePath
                - Push-Location $res_go_example_1_resourcePath
                - go get -insecure
                - Pop-Location
                - go version
            onComplete:
                - pwd
                - cd workspace
                - cd tmp
                - ls
                
      - name: publish_go_binary_1
        type: GoPublishBinary
        configuration:
          autoPublishBuildInfo: true
          forceXrayScan: true
          failOnScan: false
          inputSteps:
            - name: build_go_1
          targetRepository: go_local
          integrations:
            - name: art_v
          outputResources:
            - name: go_rak_1
             
     
