resources:
  - name: go_example_1
    type: GitRepo
    configuration:
      path: raksha78/NativeStep
      branches:
        include: powershell
      gitProvider: raksha78_github
      
       

pipelines:
  - name: go_build_pipeline_1
    configuration:
      nodePool: win_2019
    steps:
      - name: build_go_1
        type: GoBuild
        configuration:
            environmentVariables:
                JFROG_CLI_BUILD_NAME: go_example_build_publish
            sourceLocation: .
    #           resolverRepo: go_local
            repository: go_local
    #           noRegistry: true
            outputLocation: /tmp/dist/test
            outputFile: hello_output_win
            goCommand: build -o /tmp/dist/test/hello_output_win
            inputResources:
                - name: go_example_1
            integrations:
                - name: art_v
        execution:
            onStart:
                - $res_go_example_resourcePath
                - Push-Location $res_go_example_resourcePath
                - go get -insecure
                - Pop-Location
                - go version
            onComplete:
                - pwd
                - cd /tmp/dist/test
                - ls
     
       
