resources:
  - name: gradle_repository_1
    type: GitRepo
    configuration:
      gitProvider: raksha78_github
      path: raksha78/project-examples
  - name: gradle_rak_1
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: build1
      buildNumber: 1
  - name: fileSpec_001
    type: FileSpec
    configuration:
      sourceArtifactory: art_v
      pattern: fileSpec_test/install.sh
      
pipelines:
  - name: gradle_pipeline_1
    configuration:
      nodePool: win_2019
    steps:
      - name: gradle_build_step_1
        type: GradleBuild
        configuration:
          sourceLocation: gradle-examples/gradle-example-minimal
          gradleCommand: clean artifactoryPublish -b build.gradle
          configFileLocation: .
#           autoPublishBuildInfo: true
          configFileName: gradle-art-config
          inputResources:
            - name: gradle_repository_1
            - name: fileSpec_001
          integrations:
            - name: art_v
#           outputResources:
#             - name: gradle_rak_1
        execution:
          onStart:
            - javac -version
            - gradle --version
          onComplete:
            - cd dependencyState/resources/fileSpec_001
            - ls .
      - name: gradle_publish_1
        type: PublishBuildInfo
        
        configuration:
          environmentVariables: # optional
            JFROG_CLI_BUILD_NAME: "rak_test_1"
            JFROG_CLI_BUILD_NUMBER: 29
#           envInclude: buildinfo.env.*  # optional 
          envExclude: buildinfo.env.* # optional
#           forceXrayScan: <boolean/string>  # optional, defaults to false
#           failOnScan: <boolean/string>   # optional, defaults to true

          inputSteps:
            - name: gradle_build_step_1
          outputResources:
            - name: gradle_rak_1  # required BuildInfo resource  

        
