resources:
  - name: gitRepo
    type: GitRepo
    configuration:
      gitProvider: raksha78_github
      path: raksha78/charts
   
  - name: helm_repo_test
    type: HelmChart
    configuration: 
      sourceArtifactory: art_v
      repository: helm-local
      chart: test
      version: 1.0.0
      
  - name: helm_build
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildNumber: 1
      buildName: helm_build

pipelines:
  - name: test_helm

    steps:
      - name: helm_publish
        type: HelmPublish
        configuration:
          environmentVariables: # optional
            JFROG_CLI_BUILD_NAME: "rak_test"
            JFROG_CLI_BUILD_NUMBER: 28
          autoPublishBuildInfo: true
#           helmVersion: 2
#           lint: true
#           lintFlags: --help
          flags: --debug
          chartPath: stable/tomcat
          inputResources:
            - name: gitRepo                    
          outputResources:
            - name: helm_repo_test    
            - name: helm_build 
 
        execution:
          onStart:
            - echo "Preparing for work..."
           
          onSuccess:
            - echo "Job well done!"
            - helm version 
           
          onFailure:
            - echo "uh oh, something went wrong"
           
          onComplete: #always
            - echo "Cleaning up some stuff"
         
