resources:
  - name: gitRepo
    type: GitRepo
    configuration:
      gitProvider: raksha78_github
      path: raksha78/hello-helm
   
  - name: helm_repo_test
    type: HelmChart
    configuration: 
      sourceArtifactory: art_v
      repository: helm-local
      chart: tomcat
      version: 0.1.0
      
  - name: helm_build
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildNumber: 1
      buildName: helm_build

pipelines:
  - name: test_helm

    steps:
#       - name: helm_publish
#         type: HelmPublish
#         configuration:
#           environmentVariables: # optional
#             JFROG_CLI_BUILD_NAME: "rak_test"
#             JFROG_CLI_BUILD_NUMBER: 28
#           autoPublishBuildInfo: true
# #           helmVersion: 2
# #           lint: true
# #           lintFlags: --help
# #           flags: --debug
#           chartPath: stable/tomcat
#           inputResources:
#             - name: gitRepo                    
#           outputResources:
#             - name: helm_repo_test    
#             - name: helm_build 
 
      
            
      - name: HelmDeploy
        type: HelmDeploy
#         execution:
#           onStart:
#             - kubectl config set-context --current --namespace=pipe-master-pool 
        configuration:
          #inherits from bash
          helmVersion: 3      # optional, defaults to 2
#           flags: -n pipe-master-pool                   # optional
          flags: --namespace pipe-master-pool              # optional
          
#           valueFilePaths:                       # optional
#             - <path and filename>
          releaseName: test1
          chartPath: ./chart/hello
          dryRun: true   # optional, only deploys if the dryrun is success
          lint: true # lints chart before upgrade, default false
          lintFlags: --help
          test: true   # runs helm test after upgrade, default false
          testFlags: --parallel
          integrations:
            - name: kube               # required
          inputResources:
            - name: gitRepo     
          runtime:           
            type: image
            image:
              auto:
                language: node
                versions: [ 12.18.2 ]
         
