resources:
  - name: gitRepo_1
    type: GitRepo
    configuration:
      gitProvider: raksha78_github
      path: raksha78/charts
   
  - name: helm_repo_test_1
    type: HelmChart
    configuration: 
      sourceArtifactory: art_v
      repository: helm-local
      chart: test
      version: 1.0.0
  - name: helm_build_1
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildNumber: 1
      buildName: helm_build_1


pipelines:
  - name: test_helm_1
    configuration:
        nodePool: win_2019
    steps:
      - name: helm_publish_1
        type: HelmPublish
        configuration:
          environmentVariables: # optional
            JFROG_CLI_BUILD_NAME: "rak_test_1"
            JFROG_CLI_BUILD_NUMBER: 29
#           helmVersion: 2
          autoPublishBuildInfo: true
#           helmVersion: 2
#           lint: true
#           lintFlags: --help
          flags: --debug
          chartPath: stable/tomcat
          inputResources:
            - name: gitRepo_1                 
          outputResources:
            - name: helm_repo_test_1    
            - name: helm_build_1
 
        execution:
          onStart:
            - echo "Preparing for work..."
            
           
          onSuccess:
            - echo "Job well done!"
            - helm version
           
          onFailure:
            - echo "uh oh, something went wrong"
           
          onComplete: #always
            - echo "Cleaning up some stuff"
