resources:
  - name: helloHelm
    type: GitRepo
    configuration:
      gitProvider: raksha78_github
      path: raksha78/hello-helm
      branches:
        include: master
  - name: helmChart
    type: HelmChart
    configuration:
      sourceArtifactory: art_v
      repository: example-repo-local
      chart: my chart
      version: v1.1.1
      
      
pipelines:

  name: test_helm
  steps:
    - name: trigger_all_helm
      type: Bash
      execution:
        onExecute:
          - echo "test"
    - name: HelmDeploy_1
      type: HelmDeploy
      configuration:
        helmVersion: 3
        flags: '--namespace pipe-master-pool'
        releaseName: test1
        chartPath: chart/hello
        integrations:
          - name: aidan_kubernetes
        inputResources:
          - name: helloHelm
        inputSteps:
          - name: trigger_all_helm
        runtime:
          type: image
          image:
            auto:
              language: node
              versions:
                - 12.18.2
    - name: HelmDeploy_2
      type: HelmDeploy
      configuration:
        helmVersion: 3
        flags: '--namespace pipe-master-pool'
        releaseName: test1
        chartPath: chart/hello
        integrations:
          - name: aidan_kubernetes
        inputResources:
          - name: helmChart
        inputSteps:
          - name: trigger_all_helm
        runtime:
          type: image
          image:
            auto:
              language: node
              versions:
                - 12.18.2
    - name: HelmDeploy_3
      type: HelmDeploy
      configuration:
        helmVersion: 2
        flags: '--namespace pipe-master-pool'
        releaseName: test1
        chartPath: chart/hello
        integrations:
          - name: aidan_kubernetes
        inputResources:
          - name: helmChart
        inputSteps:
          - name: trigger_all_helm
        runtime:
          type: image
          image:
            auto:
              language: node
              versions:
                - 12.18.2
    - name: HelmDeploy_4
      type: HelmDeploy
      configuration:
        helmVersion: 3
        flags: '--namespace pipe-master-pool'
        releaseName: test1
        chartPath: chart/hello
        integrations:
          - name: aidan_kubernetes
        inputResources:
          - name: helmChart
        inputSteps:
          - name: trigger_all_helm
        runtime:
          type: image
          image:
            auto:
              language: node
              versions:
                - 12.18.2
    - name: HelmDeploy_5
      type: HelmDeploy
      configuration:
        flags: '--namespace pipe-master-pool'
        releaseName: test1
        chartPath: chart/hello
        integrations:
          - name: aidan_kubernetes
        inputResources:
          - name: helmChart
        inputSteps:
          - name: trigger_all_helm
        runtime:
          type: image
          image:
            auto:
              language: node
              versions:
                - 12.18.2
    - name: HelmDeploy_6
      type: HelmDeploy
      configuration:
        helmVersion: 3
        flags: '--namespace pipe-master-pool'
        releaseName: test1
        chartPath: chart/hello
        dryRun: true
        test: true
        testFlags: '--parallel'
        integrations:
          - name: aidan_kubernetes
        inputResources:
          - name: helloHelm
        inputSteps:
          - name: trigger_all_helm
        runtime:
          type: image
          image:
            auto:
              language: node
              versions:
                - 12.18.2
    - name: HelmDeploy_7
      type: HelmDeploy
      configuration:
        helmVersion: 3
        flags: '--namespace pipe-master-pool'
        releaseName: test1
        chartPath: chart/hello
        dryRun: true
        lint: true
        lintFlags: '--help'
        integrations:
          - name: aidan_kubernetes
        inputResources:
          - name: helloHelm
        inputSteps:
          - name: trigger_all_helm
        runtime:
          type: image
          image:
            auto:
              language: node
              versions:
                - 12.18.2
    - name: HelmDeploy_8
      type: HelmDeploy
      configuration:
        helmVersion: 3
        flags: '--namespace pipe-master-pool'
        releaseName: test1
        chartPath: chart/hello
        dryRun: true
        integrations:
          - name: aidan_kubernetes
        inputResources:
          - name: helloHelm
        inputSteps:
          - name: trigger_all_helm
        runtime:
          type: image
          image:
            auto:
              language: node
              versions:
                - 12.18.2
    - name: HelmDeploy_10
      type: HelmDeploy
      configuration:
        helmVersion: 3
        flags: '--namespace pipe-master-pool'
        releaseName: test1
        chartPath: chart/hello
        test: true
        testFlags: '--parallel'
        integrations:
          - name: aidan_kubernetes
        inputResources:
          - name: helloHelm
        inputSteps:
          - name: trigger_all_helm
        runtime:
          type: image
          image:
            auto:
              language: node
              versions:
                - 12.18.2
