resources:
  - name: repo_1
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                     
      path: raksha78/NativeStep
      branches:
        include: ^powershell$
  - name: docker_rak_win
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: docker_rak_win
      buildNumber: 1
  - name: fileSpec_test_1
    type: FileSpec
    configuration:     
      sourceArtifactory: art_v
      pattern: "fileSpec_test/install.ps1"
      
  - name: out_img_1
    type: Image
    configuration:
       registry: art_v
       sourceRepository: output_res  # required if Docker registry is Artifactory
       imageName: dev.jfrog-pipelines.com/output_res/img 
       imageTag: ${run_number}  

pipelines: 
  - name: dockerPipe_1
    configuration:
      nodePool: win_2019
    steps:
      - name: buildStep_1
        type: DockerBuild
        configuration:
          affinityGroup: Together
          dockerFileLocation: . # optional, defaults to .
          dockerFileName: Dockerfile    # optional, defaults to Dockerfile
          dockerImageName: dev.jfrog-pipelines.com/rak_docker/img   
          dockerImageTag:  ${run_number}    
          inputResources:
              - name: repo_1
              - name: fileSpec_test_1
      - name: pushStep_1
        type: DockerPush
        configuration:
          targetRepository: output_res 
          affinityGroup: Together
#           autoPublishBuildInfo: true
          integrations:
            - name: art_v 
          inputSteps:
            - name: buildStep_1
          outputResources:
            - name: out_img_1
