resources:
  - name: repo_1
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                     
      path: raksha78/NativeStep
      branches:
        include: ^powershell$
  - name: docker_rak_win
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: docker_rak_win
      buildNumber: 1
#   - name: fileSpec_test_1
#     type: FileSpec
#     configuration:     
#       sourceArtifactory: art_v
#       pattern: "fileSpec_test/install.ps1"
      
#   - name: out_img_1
#     type: Image
#     configuration:
#        registry: art_v
#        sourceRepository: output_res  # required if Docker registry is Artifactory
#        imageName: dev.jfrog-pipelines.com/output_res/img 
#        imageTag: ${run_number}  

pipelines: 
  - name: dockerPipe_01
    steps:
      - name: To_build_Docker_Image_2
        type: DockerBuild
        configuration:
          affinityGroup: BasicTest
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: fullstack.jfrog-pipelines.com/docker-local/node
          dockerImageTag: latest
          integrations:
            - name: art_v
          inputResources:
            - name: repo_1
            
      - name: To_Push_Docker_Image_2
        type: DockerPush
        configuration:
          affinityGroup: BasicTest
          autoPublishBuildInfo: true
          forceXrayScan: true
          failOnScan: false
          targetRepository: docker-local
          integrations:
            - name: art_v
          inputSteps:
            - name: To_build_Docker_Image_2
          outputResources:
            - name: docker_rak_win
