resources:
  - name: repo_1
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                     
      path: raksha78/NativeStep
      branches:
        include: ^powershell$
  - name: docker_rak_win
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: docker_rak_win
      buildNumber: 1

pipelines: 
  - name: dockerPipe_1
    configuration:
      nodePool: win_2019
    steps:
      - name: buildStep_1
        type: DockerBuild
        configuration:
#           affinityGroup: Together
          dockerFileLocation: . # optional, defaults to .
          dockerFileName: Dockerfile    # optional, defaults to Dockerfile
          dockerImageName: dev.jfrog-pipelines.com/rak_docker/img   
          dockerImageTag:  ${run_number}    
          inputResources:
              - name: repo_1
#       - name: pushStep_1
#         type: DockerPush
#         configuration:
#           targetRepository: rak_docker 
#           affinityGroup: Together
#           autoPublishBuildInfo: true
#           integrations:
#             - name: art_v 
#           inputSteps:
#             - name: buildStep_1
#           outputResources:
#             - name: docker_rak_win
