resources:
  - name: repo
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                     
      path: raksha78/NativeStep
      branches:
        include: ^linux$
  
#   - name: fileSpec_test_
#     type: FileSpec
#     configuration:     
#       sourceArtifactory: art_v
#       pattern: "fileSpec_test/install.sh"
       
  - name: docker_rak_linux
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: docker_rak_linux
      buildNumber: 1
      
  - name: connecting_resource
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

#   - name: out_img
#     type: Image
#     configuration:
#        registry: art_v
#        sourceRepository: output_res  # required if Docker registry is Artifactory
#        imageName: dev.jfrog-pipelines.com/rak_docker/img 
# #        imageName: fullstack.jfrog-pipelines.com/rak_docker/img 
#        imageTag: ${run_number}  
       



pipelines: 
  - name: dockerPipe
    steps:
      - name: To_build_Docker_Image_1
        type: DockerBuild
        configuration:
          affinityGroup: BasicTest
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: fullstack.jfrog-pipelines.com/docker-local/node
          dockerImageTag: latest
          integrations:
            - name: art_v
          inputResources:
            - name: repo
            - name: connecting_resource_1
            
      - name: To_Push_Docker_Image_1
        type: DockerPush
        configuration:
          affinityGroup: BasicTest
          autoPublishBuildInfo: true
          forceXrayScan: true
          failOnScan: false
          targetRepository: docker-local
          integrations:
            - name: art_v
          inputSteps:
            - name: To_build_Docker_Image_1
          outputResources:
            - name: docker_rak_linux
            
