resources:
#   - name: repo
#     type: GitRepo
#     configuration:
#       gitProvider: raksha78_github                     
#       path: raksha78/NativeStep
#       branches:
#         include: ^linux$
  
  - name: fileSpec_test
    type: FileSpec
    configuration:     
      sourceArtifactory: art_v
      pattern: "fileSpec_test/Dockerfile"
       
#   - name: docker_rak_linux
#     type: BuildInfo
#     configuration:
#       sourceArtifactory: art_v
#       buildName: docker_rak_linux
#       buildNumber: 1


pipelines: 
  - name: dockerPipe_01
    steps:
#       - name: buildStep
#         type: DockerBuild
#         configuration:
#           dockerFileLocation: . # optional, defaults to .
#           dockerFileName: Dockerfile    # optional, defaults to Dockerfile
#           dockerImageName: dev.jfrog-pipelines.com/rak_docker/img   
#           dockerImageTag:  ${run_number}    
#           inputResources:
#               - name: repo 
      - name: dowload_linux_1
        type: Bash
        configuration:
          integrations:
            - name: art_v
          inputResources:
#             - name: connecting_resource
            - name: fileSpec_test
        execution:
          onExecute:
            - echo $res_fileSpec_test_resourcePath
            - ls $res_fileSpec_test_resourcePath
#       - name: pushStep
#         type: DockerPush
#         configuration:
#           targetRepository: rak_docker 
#           affinityGroup: Together
#           autoPublishBuildInfo: true
#           integrations:
#             - name: art_v 
#           inputSteps:
#             - name: buildStep  
#           outputResources:
#             - name: docker_rak_linux
            
            
